{"name": "test_vwo_login_positive", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestVWOLogin' object has no attribute 'pyatb3x'", "trace": "self = <tests.test.vwoLoginTests.test_vwo_login_pf.TestVWOLogin object at 0x000001856BE22660>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"56ffa8764b55daf493116d944130f5ed\")>\n\n    @pytest.mark.usefixtures(\"setup\")\n    @pytest.mark.qa\n    def test_vwo_login_positive(self, setup):\n        driver = setup\n        driver.get(Constants.app_url())\n        login_page = LoginPage(driver)\n>       login_page.login_to_vwo(user=self.pyatb3x@wingify.com, pwd=self.password)\nE       AttributeError: 'TestVWOLogin' object has no attribute 'pyatb3x'\n\ntests\\test\\vwoLoginTests\\test_vwo_login_pf.py:38: AttributeError"}, "start": 1726039116322, "stop": 1726039118277, "uuid": "267ee133-e164-4f59-8901-2345543fff28", "historyId": "6109efe96f903dc20f391c57b0ade122", "testCaseId": "6109efe96f903dc20f391c57b0ade122", "fullName": "tests.test.vwoLoginTests.test_vwo_login_pf.TestVWOLogin#test_vwo_login_positive", "labels": [{"name": "feature", "value": "Login Test"}, {"name": "epic", "value": "VWO App"}, {"name": "tag", "value": "qa"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.test.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login_pf"}, {"name": "subSuite", "value": "TestVWOLogin"}, {"name": "host", "value": "Chaitra"}, {"name": "thread", "value": "24220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.vwoLoginTests.test_vwo_login_pf"}]}